name: deploy-cookbook

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
  
# This job installs dependencies, builds the cookbook 
# and pushes the html files to `gh-pages` branch
jobs:
  deploy-cookbook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup python
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the docs
    - name: Build the book
      run: |
        make html
        
      # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
